### ISSUE TITLE
Why object type should be passed as String and not directly be a constant ?

### ISSUE THREAD

**Issue by Pagehey** [sunny/actor#16]
Hi there,

First of all, thank you for your work. I find it really cool and looks like a good solution to improve basic service objects.

My question here is: why can't we pass directly constants to check the type of inputs and should pass it as string instead ?

like this:
```ruby
class GreetUser < Actor
  input :user, type: User

  def call
    puts "Hello #{user.name}!"
  end
end
```
I didn't find any reason in the code of the gem or I am ignorant about a deeper problem.

All I found about this is in `lib/actor/type_checkable.rb`: 
```ruby
types = Array(type_definition).map { |name| Object.const_get(name) }
```
which confirms to me we could pass directly constant instead of String since you "constantize" it anyway.

looking forward to your reply,
thanks !
Pagehey

**Comment by sunny** [comment]
Hey @Pagehey! Indeed the gem allows you to use both `type: 'User'` and `type: User` even though it's not documented.

The reasoning behind using strings is that I have encountered issues before because of the way constant loading can sometimes too eagerly load your whole app and end up in a tangled mess.

I think I'll change the documentation to invite people to use classes directly but add a small explanation to say that it can accept strings as well.

**Comment by sunny** [comment]
Actually `Object.const_get(name)` does not work when "name" is already a constant. I'll fix the gem in that regard.
